### ISSUE TITLE
Changing Bounding Size of Full Block

### ISSUE THREAD

**Issue by Mattabase** [GirafiStudios/Impractical-Storage#7] opened 2017-03-24 12:40 UTC
https://goo.gl/DwHV1G

Happened when I changed the bounds of the Storage Controller while it was full. 

Not able to get it to happen reliably though.

**Comment by dmillerw** [comment] 2017-03-25 03:36
I kind of want to say this is an MC issue. I can't track down the cause just yet

**Comment by Flabort** [comment] 2017-03-27 23:27
I wonder... did you SHRINK the full storage, or how did you do it?

**Comment by dmillerw** [comment] 2017-03-29 05:52
_should_ be fixed by 83114740900ac423f534aa78d300cd9829a6190d

**Closed as completed** 2017-03-29 21:36 UTC
Labels: confirmed-bug, medium-priority, fixed (need confirmation)
